### ISSUE TITLE
why there is no `from accelerate import Accelerator` in code

### ISSUE THREAD

**Issue by IcyFeather233** [whyNLP/tinyllama#4]
Hi I am new to accelerate, so maybe my question is a little silly. I find that the [hugginface accelerate github doc](https://github.com/huggingface/accelerate) reads that:

```python
  import torch
  import torch.nn.functional as F
  from datasets import load_dataset
+ from accelerate import Accelerator

+ accelerator = Accelerator()
- device = 'cpu'
+ device = accelerator.device

  model = torch.nn.Transformer().to(device)
  optimizer = torch.optim.Adam(model.parameters())

  dataset = load_dataset('my_dataset')
  data = torch.utils.data.DataLoader(dataset, shuffle=True)

+ model, optimizer, data = accelerator.prepare(model, optimizer, data)

  model.train()
  for epoch in range(10):
      for source, targets in data:
          source = source.to(device)
          targets = targets.to(device)

          optimizer.zero_grad()

          output = model(source)
          loss = F.cross_entropy(output, targets)

-         loss.backward()
+         accelerator.backward(loss)

          optimizer.step()
```

However there seems no `accelerate` in your code:

```
    # Training
    if training_args.do_train:
        checkpoint = None
        if training_args.resume_from_checkpoint is not None:
            checkpoint = training_args.resume_from_checkpoint
        elif last_checkpoint is not None:
            checkpoint = last_checkpoint
        train_result = trainer.train(resume_from_checkpoint=checkpoint)
        trainer.save_model()  # Saves the tokenizer too for easy upload

        metrics = train_result.metrics

        max_train_samples = (
            data_args.max_train_samples if data_args.max_train_samples is not None else len(train_dataset)
        )
        metrics["train_samples"] = min(max_train_samples, len(train_dataset))

        trainer.log_metrics("train", metrics)
        trainer.save_metrics("train", metrics)
        trainer.save_state()
```

I wonder if it's some special method to use accelerate?

**Comment by why-in-Shanghaitech** [comment]
Hi! Thank you for the question. I believe that there is no need to explicitly write accelerate codes since we are using the huggingface trainer. It will call accelerate functions in the train loop:

https://github.com/huggingface/transformers/blob/514de24abfd4416aeba6a6455ad5920f57f3567d/src/transformers/trainer.py#L1683-L1694

**Comment by IcyFeather233** [comment]
Thank you so much!

**Comment by IcyFeather233** [comment]
Hi I have another question about accelerate: what parallelism method accelerate use?

For example, when I use `deepspeed run_clm.py` I know its zero optimization method in `ds_config.json`, but when I use `acccelerate launch`, what parallelism method it automatically used?

**Comment by why-in-Shanghaitech** [comment]
Hi! Thank you for the question. By default the script uses ddp. This has nothing to do with accelerate. To verify this, you may launch the script with `python run_clm.py` instead of `accelerate launch run_clm.py`. It should still work on multiple cards.

> Accelerate automatically selects the appropriate configuration values for any given distributed training framework (DeepSpeed, FSDP, etc.) through a unified configuration file generated from the [accelerate config](https://huggingface.co/docs/accelerate/package_reference/cli#accelerate-config) command. You could also pass the configuration values explicitly to the command line which is helpful in certain situations like if you’re using SLURM.

See https://huggingface.co/docs/accelerate/basic_tutorials/launch#using-accelerate-launch

Here we let accelerate to select the config automatically:

> You can also use accelerate launch without performing accelerate config first, but you may need to manually pass in the right configuration parameters. In this case, 🤗 Accelerate will make some hyperparameter decisions for you, e.g., if GPUs are available, it will use all of them by default without the mixed precision.

See https://huggingface.co/docs/accelerate/basic_tutorials/launch#using-accelerate-launch

**Comment by IcyFeather233** [comment]
Thanks so much!
